[package]
name = "dgfl-native"
version = "0.1.0"
edition = "2021"

[lib]
name = "dgfl_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.5", features = ["extension-module"] }
ark-bls12-381 = "0.4.0"
ark-serialize = "0.4.0"
ark-ec = "0.4.0"
ark-ff = { version = "0.4.0", features = ["asm"] }
hex = "0.4"

[profile.release]
lto = "thin"
codegen-units = 1
